swagger: '2.0'
info:
  version: 1.0.0
  title: Codenames Game
# host: boardstore.swagger.io
# basePath: /v2
# schemes:
# - http
paths:
  /board:
    post:
      summary: Add a new board
      operationId: addboard
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: board object that needs to be added to the store
        required: true
        schema:
          $ref: '#/definitions/board'
      responses:
        405:
          description: Invalid input
  /board/{boardId}:
    get:
      summary: Find board by ID
      description: Returns a single board
      operationId: getboardById
      produces:
      - application/json
      parameters:
      - name: boardId
        in: path
        description: ID of board to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/board'
        400:
          description: Invalid ID supplied
        404:
          description: board not found
    post:
      summary: Updates a board in the store with form data
      operationId: updateboardWithForm
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: boardId
        in: path
        description: ID of board that needs to be updated
        required: true
        type: integer
        format: int64
      - name: name
        in: formData
        description: Updated name of the board
        required: false
        type: string
      - name: status
        in: formData
        description: Updated status of the board
        required: false
        type: string
      responses:
        405:
          description: Invalid input
definitions:
  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Category
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  board:
    type: object
    required:
    - name
    - photoUrls
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        xml:
          name: photoUrl
          wrapped: true
        items:
          type: string
      status:
        type: string
        description: board status in the store
        enum:
        - available
        - pending
        - sold
    xml:
      name: board
host: virtserver.swaggerhub.com
# basePath: /codenames-dev/codenames-dev/1.0.0
schemes:
 - https
 - http
# Added by API Auto Mocking Plugin
basePath: /codenames-dev/codenames61-api/1.0.0
